/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author Sanja
 */
public class Calculator extends javax.swing.JFrame {
     
    double result;
    double firstNumber;
    double secondNumber;
    String operator;
    double mr;
    String str;
    String wthZero;
    
    
    public Calculator() {
        initComponents();
        panel.setText("0");
        panel.setEditable(false);
        
        panel.setText(wthZero);
       
    }
     public String wrd(){
         try{
        str = panel.getText().substring((panel.getText().length()-2),(panel.getText().length()-1));
        if (str.equals(".0"))
        {
        wthZero=panel.getText().replace(str,"");
        
     }
         }catch(Exception e){
         }
         return wthZero;
        
    
     }
     /*public String wrd(){
         try{
        str = panel.getText().substring((panel.getText().length()-2),(panel.getText().length()-1));
        if (str.equals(".0"))
        {
       int wthZero=Integer.parseInt(panel.getText());
       
       
     }
        }
         
        catch(Exception e){}
         return wthZero;
     }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTextField();
        one = new javax.swing.JButton();
        four = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        two = new javax.swing.JButton();
        five = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        div = new javax.swing.JButton();
        three = new javax.swing.JButton();
        six = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        sqr = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        negative = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        erase = new javax.swing.JButton();
        memory = new javax.swing.JButton();
        memorize = new javax.swing.JButton();
        mMinus = new javax.swing.JButton();
        result3 = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        ctg = new javax.swing.JButton();
        tg = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        one.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        one.setText("1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });

        four.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });

        seven.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seven.setText("7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setText("C");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });

        two.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });

        five.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        five.setText("5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });

        eight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });

        div.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        div.setText("/");
        div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divMouseClicked(evt);
            }
        });

        three.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });

        six.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });

        nine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });

        dot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dot.setText(".");
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMouseClicked(evt);
            }
        });

        plus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plus.setText("+");
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
        });

        minus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        minus.setText("-");
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
        });

        multi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        multi.setText("*");
        multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiMouseClicked(evt);
            }
        });

        sqr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sqr.setText("x²");
        sqr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sqrMouseClicked(evt);
            }
        });

        sqrt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sqrt.setText("√");
        sqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sqrtMouseClicked(evt);
            }
        });

        percent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        percent.setText("%");
        percent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentMouseClicked(evt);
            }
        });

        negative.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        negative.setText("+/-");
        negative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negativeMouseClicked(evt);
            }
        });

        ce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ce.setText("CE");
        ce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceMouseClicked(evt);
            }
        });

        erase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        erase.setText("ER");
        erase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eraseMouseClicked(evt);
            }
        });

        memory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        memory.setText("MR");
        memory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memoryMouseClicked(evt);
            }
        });

        memorize.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        memorize.setText("M+");
        memorize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memorizeMouseClicked(evt);
            }
        });

        mMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMinus.setText("M-");
        mMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMinusMouseClicked(evt);
            }
        });

        result3.setBackground(new java.awt.Color(51, 255, 0));
        result3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        result3.setText("=");
        result3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                result3MouseClicked(evt);
            }
        });

        sin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sin.setText("sin");
        sin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinMouseClicked(evt);
            }
        });

        cos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cos.setText("cos");
        cos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosMouseClicked(evt);
            }
        });

        ctg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctg.setText("ctg");
        ctg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctgMouseClicked(evt);
            }
        });

        tg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tg.setText("tg");
        tg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgMouseClicked(evt);
            }
        });

        exit.setBackground(new java.awt.Color(102, 255, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setText("exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(memorize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ctg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(erase, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(result3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(result3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(panel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erase, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memorize, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ctg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        
         
        panel.setText(panel.getText()+"1");
     
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
       if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"2");
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
       if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"3");
    }//GEN-LAST:event_threeMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"4");    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"5");    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"6");    }//GEN-LAST:event_sixMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"7");        // TODO add your handling code here:
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"8");    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"9");    }//GEN-LAST:event_nineMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        if((panel.getText().equals("0"))&&(panel.getText().length()== 1)){
        panel.setText("");
        } 
        panel.setText(panel.getText()+"0");        // TODO add your handling code here:
    }//GEN-LAST:event_zeroMouseClicked

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
       firstNumber=Double.parseDouble(panel.getText());  
          
        panel.setText("");
        operator="+";
    }//GEN-LAST:event_plusMouseClicked

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked
           firstNumber=Double.parseDouble(panel.getText());   
           panel.setText("");
            operator="-";
    }//GEN-LAST:event_minusMouseClicked

    private void sqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqrtMouseClicked
       
        double dpanel=Double.parseDouble(panel.getText());
        double root=Math.sqrt(dpanel);
        String rootw=String.valueOf(root);
        panel.setText(rootw);
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrtMouseClicked

    private void sqrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqrMouseClicked
         double dpanel=Double.parseDouble(panel.getText());
         double sq=dpanel*dpanel;
        String sqw=String.valueOf(sq);
        panel.setText(sqw);
         
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrMouseClicked

    private void multiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiMouseClicked
       firstNumber=Double.parseDouble(panel.getText());  
          
        panel.setText("");
        operator="*";
        // TODO add your handling code here:
    }//GEN-LAST:event_multiMouseClicked

    private void divMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseClicked
       firstNumber=Double.parseDouble(panel.getText());  
          
        panel.setText("");
        operator="/";
        // TODO add your handling code here:
    }//GEN-LAST:event_divMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        panel.setText("0");  
        panel.setEditable(true);
    }//GEN-LAST:event_resetMouseClicked

    private void dotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseClicked
        // TODO add your handling code here:
       if (!panel.getText().contains(".")){panel.setText(panel.getText()+"."); 
       } else {
           panel.setText(panel.getText());
        }
    }//GEN-LAST:event_dotMouseClicked

    private void ceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceMouseClicked
       panel.setText("0");  // TODO add your handling code here:
    }//GEN-LAST:event_ceMouseClicked

    private void negativeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negativeMouseClicked
       double negativ=Double.parseDouble(panel.getText());
       result=negativ*(-1);
       panel.setText(String.valueOf(result));
    }//GEN-LAST:event_negativeMouseClicked

    private void result3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_result3MouseClicked
        
        secondNumber=Double.parseDouble(panel.getText());
       
        if(operator=="+"){
            result=firstNumber+secondNumber;
            panel.setText(String.valueOf(result));
             
        }
        else if(operator=="%"){
        result=(firstNumber/100)*secondNumber;
            panel.setText(String.valueOf(result));
        }
        else if(operator=="-"){
        result=firstNumber-secondNumber;
            panel.setText(String.valueOf(result));
        }
        else if(operator=="*"){
        result=firstNumber*secondNumber;
        if(secondNumber==0){
            result=0;
        }            panel.setText(String.valueOf(result));
        }
         
       
        else if(operator=="/"){
            result=firstNumber/secondNumber;
           
            if(secondNumber==0){
                JOptionPane.showMessageDialog(null, "Wrong input!");
            
        } 
           
            else{panel.setText(String.valueOf(result));}
            
    }//GEN-LAST:event_result3MouseClicked
        
         else if(operator=="sin"){
            result=Math.sin(firstNumber);
           
           panel.setText(String.valueOf(result));
    }   
         else if(operator=="cos"){
            result=Math.cos(firstNumber);
           
           panel.setText(String.valueOf(result));
    }   
            else if(operator=="tg"){
            result=Math.tan(firstNumber);
           
           panel.setText(String.valueOf(result));
    }   
        
          else if(operator=="cot"){
            result=Math.cos(firstNumber)/Math.sin(firstNumber);
           
           panel.setText(String.valueOf(result));
    }   
       
       
    }
      
        

        
    private void memorizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memorizeMouseClicked
        mr=Double.parseDouble(panel.getText()); 
        // TODO add your handling code here:
    }//GEN-LAST:event_memorizeMouseClicked

    private void memoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryMouseClicked
        panel.setText(String.valueOf(mr));
    }//GEN-LAST:event_memoryMouseClicked

    private void mMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMinusMouseClicked
       mr=0;
        String mrMinus=String.valueOf(mr);
      panel.setText(mrMinus);
    }//GEN-LAST:event_mMinusMouseClicked

    private void percentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentMouseClicked
       firstNumber=Double.parseDouble(panel.getText()); 
       panel.setText("");
       operator="%";
    }//GEN-LAST:event_percentMouseClicked

    private void eraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eraseMouseClicked
       String p=panel.getText();
        
        String del=p.substring(0,p.length()-1);
       panel.setText(del);
    }//GEN-LAST:event_eraseMouseClicked

    private void sinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinMouseClicked
        firstNumber=Double.parseDouble(panel.getText());
        operator="sin";
    }//GEN-LAST:event_sinMouseClicked

    private void cosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosMouseClicked
        firstNumber=Double.parseDouble(panel.getText());
        operator="cos";
    }//GEN-LAST:event_cosMouseClicked

    private void tgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgMouseClicked
       firstNumber=Double.parseDouble(panel.getText());
        operator="tg";
    }//GEN-LAST:event_tgMouseClicked

    private void ctgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctgMouseClicked
         firstNumber=Double.parseDouble(panel.getText());
        operator="cot";
    }//GEN-LAST:event_ctgMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
      
    System.exit(0);
// this.setVisible(false);
    }//GEN-LAST:event_exitMouseClicked
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ce;
    private javax.swing.JButton cos;
    private javax.swing.JButton ctg;
    private javax.swing.JButton div;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton erase;
    private javax.swing.JButton exit;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton mMinus;
    private javax.swing.JButton memorize;
    private javax.swing.JButton memory;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton negative;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JTextField panel;
    private javax.swing.JButton percent;
    private javax.swing.JButton plus;
    private javax.swing.JButton reset;
    private javax.swing.JButton result3;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton sqr;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton tg;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
